version: '3.0'
services:
  orders: #container_name
    image: 208996231/company:orders
    ports:
      - "9094:4000"
    networks: # connect my orders container to the network i created
      - my_network
    environment:
      WORKERS_API: "workers:80"
  workers:
    image: 208996231/company:workers
    ports:
      - "9092:80"
    networks:
      - my_network
networks:
  my_network:
